# Generated by Django 4.1.3 on 2022-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toldi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNjoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theJoke', models.CharField(max_length=1000)),
            ],
        ),
    ]
