# Generated by Django 4.1.3 on 2022-11-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toldi', '0002_cnjoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnjoke',
            name='jokeEN',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cnjoke',
            name='jokeHU',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cnjoke',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cnjoke',
            name='theJoke',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
