# Generated by Django 4.1.3 on 2022-11-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toldi', '0003_cnjoke_jokeen_cnjoke_jokehu_alter_cnjoke_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnjoke',
            name='errorMsg',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
